name: Optimized Build Container Image

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/**"
    exclude:
      - "blogs/**"
      - "dataFeeder/**"
  workflow_run:
    workflows: ["Save Tokens to Azure KV"]
    branches: [main]
    types:
      - completed
  pull_request:
    branches: ["main"]

jobs:
  # ---------- Optimization: Parallel Test Suites Execution (if applicable) ----------
  # Assuming multiple test suites are present, otherwise this would not be applicable.
  # (Note: Placeholder steps for parallel test execution)
  
  test-suite-1:
    runs-on: ubuntu-latest
    # ... Test suite specific steps ...

  test-suite-2:
    runs-on: ubuntu-latest
    # ... Test suite specific steps ...

  # ---------- Optimization: Cache Dependencies & Build Outputs ----------
  build-and-publish:
    runs-on: ubuntu-latest
    needs: [test-suite-1, test-suite-2] # Dependency added if test suites must pass before build
    outputs:
      newtag: ${{ steps.export_tag.outputs.sha }}
      shorttag: ${{ steps.export_tag.outputs.short }}
    steps:
      - uses: actions/cache@v2 # Implementing caching of dependencies
        with:
          path: |
            ~/.m2/repository
            ~/.npm
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      
      - name: Export sha as short tag
        id: export_tag
        run: |
          export "SHA=${{ github.sha }}"
          echo $SHA
          echo "${SHA:0:7}"
          export "SHORT=${SHA:0:7}}"
          echo "sha=${{github.sha}}" >> $GITHUB_OUTPUT
          echo "short=${SHORT}}" >> $GITHUB_OUTPUT

      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3

      # ... Other build and publish steps ...

  # ---------- Optimization: Removed Redundant Tasks, Streamlined Workflow ----------
  update-deployed-image-tag:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      # Checkout step, Kustomize installation, Kustomize steps are optimized as before
      # No changes required unless steps identified as redundant or could be optimized further
      
      # ... Steps remain as were in the original workflow ...
