name: Build Data Source Container

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "blogs/**"
      - "dataFeeder/**"
  workflow_run:
    workflows: ["Save Tokens to Azure KV"]
    branches: [main]
    types:
      - completed
  pull_request:
    branches: ["main"]
    paths:
      - "blogs/**"
      - "dataFeeder/**"

jobs:
  build-data-sources:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build') || github.event_name == 'push'

    outputs:
      newtag: ${{ steps.export_tag.outputs.sha }}
      shorttag: ${{ steps.export_tag.outputs.short }}

    steps:
      # Exports the commit SHA for tagging the Docker image
      - name: Export sha as short tag
        id: export_tag
        run: |
          export "SHA=${{ github.sha }}"
          export "SHORT=${SHA:0:7}"
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "short=${SHORT}" >> $GITHUB_OUTPUT

      # Build and push the Docker image only if there are changes
      - name: Build, Tag and Push Docker Image to GHCR
        uses: docker/build-push-action@v2
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && (steps.file_changes.outputs.blogs == 'true' || steps.file_changes.outputs.datafeeder == 'true'))
        with:
          context: .
          file: ./dataFeeder/Dockerfile-dataFeeder
          push: true
          tags: |
            xgeeks-geekathon/ai-starter-template-datafeeder:${{ steps.export_tag.outputs.short }}
            xgeeks-geekathon/ai-starter-template-datafeeder:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-deployed-data-container-tag:
    runs-on: ubuntu-latest
    needs: build-data-sources
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: xgeeks-geekathon/ai-starter-template_deployment
          token: ${{ secrets.IDP_TOKEN }}

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Kustomize deployment image tag
        env:
          NEW_TAG: ${{ needs.build-data-sources.outputs.newtag }}
          SHORT_TAG: ${{ needs.build-data-sources.outputs.shorttag }}
        run: |
          cd k8s/overlays/dev
          kustomize edit set image ghcr.io/xgeeks-geekathon/ai-starter-template-datafeeder:${{ env.SHORT_TAG }}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "ci: update datafeeder image tag to '${{ env.SHORT_TAG }}'"
          git push
